
website:
  reader-mode: true
  description: " " # a brief slogan (optional)
  image: img/my_image.jpeg
  favicon: img/ocfavicon3.png
  google-analytics: "G-NDNR3PY3JP"
  
  navbar:
    pinned: true
    collapse: true
    logo: img/ocfavicon3.png
    # sub-pages
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        href: resume/index.qmd
      - text: "Projects"
        href: blog_index.qmd
      - text: "Resources"
        menu: 
          - text: "Web-based Sources"
            href: resources/index.qmd
          - text: "Math Learning Plan"
            href: resources/lindex.qmd
          - text: "Advance Math & Techniques"
            href: resources/mathforDS.qmd
          - text: "Recommended Books"
            href: resources/books/index.qmd
      - text: "My Blog"
        href: https://theupsidedownblog.netlify.app
        target: _blank
        
    # social media handles
    right:
      - icon: journal-bookmark
        aria-label: Blog
        href: https://theupsidedownblog.netlify.app
        target: _blank
      - icon: award
        href: https://meritpages.com/ocardec
        target: _blank
      - icon: twitter
        href: https://twitter.com/CardO37474
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/oscarcardec/
        target: _blank
      - icon: envelope-at
        aria-label: email
        href: "mailto:ocmain@gocardec.com"  
        
# Don't touch unless you know what you're doing :) ========================
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; Copyright 2025 Cardec Solutions</span>
    center: |
          <span class="faux-block">Created in <a href="https://quarto.org" target="_blank"> <img src="/img/quarto.png" width="75"></a></span>
    right: |
      <span class="faux-block">Mar 2025</span>

project:
  type: website
  output-dir: docs
  preview: 
    port: 2727
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto

format:
  html:
    page-layout: full
    fontsize: 1.1em
    theme:
      light: flatly
      dark: darkly
    css: html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    embed-resources: true

editor: visual
