# File to control the settings of ocquarto_portfolio by OC

# Website settings:
website:
  reader-mode: true
  description: " " # a brief slogan (optional)
  image: img/my_image.jpeg
  favicon: img/ocfavicon2.jpg
  navbar:
    pinned: true
    collapse: true
    logo: img/ocfavicon2.jpg
    # sub-pages
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        href: resume/index.qmd
      - text: "Projects"
        href: blog_index.qmd
      - text: "Resources"
        href: resources/index.qmd
      - text: "Books"
        href: books/index.qmd
        
    # social media handles
    right:
      - icon: folder-symlink
        href: https://meritpages.com/ocardec
      - icon: twitter
        href: https://twitter.com/CardO37474
      - icon: linkedin
        href: https://www.linkedin.com/in/oscarcardec/
      - icon: envelope
        aria-label: email
        href: "mailto:ocmain@gocardec.com"  
        
# Don't touch unless you know what you're doing :) ========================
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; Copyright 2024 Oscar Cardec</span>
    right: |
      <span class="faux-block">Last Update: Jul 2024</span>

project:
  type: website
  output-dir: docs
  preview: 
    port: 2727
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto

format:
  html:
    page-layout: full
    fontsize: 1.1em
    theme: 
      - Flatly
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    embed-resources: true

editor: visual
