# OSCAR CARDEC

| Williamsburg, Virginia
| [ocmain\@gocardec.com](mailto:ocmain@gocardec.com)
| 443.296.2380

------------------------------------------------------------------------

## PROFESSIONAL SUMMARY

Highly experienced Data Analyst and Machine Learning Specialist combining over 20 years of military experience and comprehensive knowledge across data analytics, machine learning, deep learning, and Generative AI. Specializing in data pipelines, data exploration, data pre-processing, data analysis, visualizations and data modeling with both structured and unstructured sources. Proven ability to translate stakeholder requirements and pain-points into actionable data science solutions. Expert in leading discussions across functions, building data science credibility, and mentoring teams in critical thinking, root cause analysis and problem-solving to enable decision-making at public and private sectors. Active security clearance and extensive experience supporting federal clients.

## CORE COMPETENCIES

| • **Machine Learning:** Applied AI, predictive modeling, generative AI, and anomaly detection
| • **Data Analysis:** Exploratory analysis, data cleaning, statistical inferences, and complex visualizations
| • **Strategic Leadership:** Decision analysis, critical thinking, and project management
| • **Technical Expertise:** Advanced proficiency in Python, R, Power BI, and cloud-based tools

## PROFESSIONAL EXPERIENCE

#### **Data Scientist \| ManTech International Corporation (Sep 2024 – Present)**
| • Performs hands-on analysis and modeling involving the creation of intervention hypotheses and experiments, assessment of data needs and available sources, determination of optimal analytical approaches, performance of exploratory data analysis, and feature generation 

| • Collaborates with mission stakeholders to define, frame, and scope mission challenges. Strategize best way forward for extracting, cleaning, and transforming operational and transactional data to build descriptive and predictive models/analytics in order to inform mission directors. Capture data inferences and communicate them via Palantir Envision foundry, PowerBI interactive dashboards, and/or PowerApps customized applications. 

#### **Data Scientist - R&D Strategist \| Webworld Technologies, Inc. (Jul 2023 – Sep 2024)**

| • Directed cloud solution research, market analysis, and data migration, ensured operational integrity.
| • Steered Enterprise Data Management Plan review and implementation in support of the ACC & DAF.
| • Developed strategies for data catalog and data governance in line with DoD VAULTIS guidelines.
| • Overhauled ML practices and data mining strategies; standardized decision-making, workflow analysis.
| • Created and optimized data taxonomies/ontologies, and audited cloud capabilities for analytic solutions.

#### **Data Scientist - ML Specialist \| GovCIO (Feb 2023 – Jul 2023)**

| • Directed machine learning projects, utilizing data mining and anomaly detection to uncover insights.
| • Led quantitative analysis using operations research tools and time-series forecasting.
| • Conducted training on Splunk MLTK and integrated it into daily operations, transformed probabilistic measures to detect network traffic interruptions.

#### **Lead Data Scientist \| Deloitte & Touché, LLP. (Apr 2021 – Feb 2023)**

| • Spearheaded data analysis for DHS/CBP, optimizing assets allocations through historical data insights.
| • Implemented machine learning models and provided mentoring to junior staff.
| • Developed K-means algorithms for public health initiatives and led analytic proof of concept projects.
| • Advanced analytic practices for ACC Force Generation, improved data strategy and data sources ingestion.
| • Conducted social network analysis, topic modeling, and sentiment analysis, advanced analytical practices.

#### **Data Science Intern \| Accenture Federal Services (Oct 2020 – Jan 2021)**

| • Sustained national security operations by employing novel natural language processing, social media and web content scraping, topic mining, and sentiment analysis techniques.
| • Utilized exploratory data analysis tradecraft and machine learning procedures to uncover hidden data, meeting client's information requests.

#### **Senior Data Analyst, Intelligence Operations \| United States Air Force (May 2014 – Mar 2021)**

| • Managed intelligence collection functions, improving operational capabilities by 85%.
| • Delivered over 1200 intelligence briefs to senior leadership.
| • Directed the allocation and training of 2,600 Intelligence Analysts, enhancing workforce efficiency.
| • Supervised 1,300 personnel in ISR missions and managed DCGS programs.
| • Led joint teams in foreign missile analysis and multi-source data extraction.
| • Oversaw counter-terrorism operations, assessing global targets and cyber objectives.
| • Directed counter-proliferation analysis and reporting, leading to international sanctions.
| • Coordinated Force Protection across national organizations, ensuring the safe return of personnel.

## EDUCATION

**Master of Science in Data Analytics (MSDA) \| University of Maryland, Global Campus**

| • Integrated Support Vector Machine (SVM) and K-Nearest Neighbors (KNN) heuristic algorithms to enhance Federal Aviation Administration’s NextGen R&D Office aircraft’s lateral deviation anomaly detection tools.
| • Designed Conditional Inference Tree (CTREE) for classification and interpretation of CTGs, optimizing identification of at-risk newborns and their mothers.
| • Developed an irregular-cells Convolutional Neural Network (CNN) predictive model for early detection of breast carcinoma.
| • Classified Landsat Multispectral Scanner images using K-means model, base-lining image study with vector/centroid pixel- dimension features.

<br/>

**Bachelor of Science in Information Technology Management \| American Military University**

| • Applied industry driven techniques throughout complete IT project's development lifecycle
| • Applied principles and practices of business solutions, database systems, networks, information systems, information security, and information technology project planning

## TECHNICAL COMPETENCIES

| • **Programming:** Python, R, SQL, C#, MATLAB, SAS, VSC, Git, TensorFlow, Keras, PyTorch
| • **Data Science Tools:** Scikit-learn, Pandas, Numpy, Seaborn, Matplotlib, Plotly, Tidyverse
| • **Cloud & BI:** Azure, AWS, GCP, KNIME, Qlik, Tableau, Power BI, PowerApps, IBM Cognos Analytics, SAS E-Miner
| • **Machine Learning:** Time series forecasting, econometric models, classification techniques
| • **Development:** Shiny, Quarto, Rmarkdown, Dash, Boken, Streamlit, Flask

<br/>

**Data Science Additional Packages**\
beautifulsoup, caret, docker, dv-api, faker, geopandas, ggmap, gmodels, googlevis, ggvis, graphDB, H2O, iml, korpus, label studio, mobi, mysql, nltk, oneR, parallel, protégé, pyspark, pytorch, quanteda, ranger, scipy, scrapy, selenium, simpy, sdv, splunk mltk, spyder, spacy, sql, sqlite3, statsmodels, Tesseract OCR, tidygraph, tm, vip, xgboost, zoo
